"""
Document Generator Module.
Generates DOCX exports for checklists and eligibility reports.
"""

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import io
import os
import zipfile
import zipfile
from datetime import datetime


def generate_checklist_docx(tender_title: str, checklist_data: str) -> io.BytesIO:
    """
    Generate a formatted DOCX checklist from extracted checklist text.
    """
    doc = Document()
    
    # Title
    title = doc.add_heading("Bid Preparation Checklist", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Metadata
    doc.add_paragraph(f"Tender: {tender_title}")
    doc.add_paragraph(f"Generated: {datetime.now().strftime('%d-%m-%Y %H:%M')}")
    doc.add_paragraph("─" * 60)
    
    # Parse checklist content into formatted paragraphs
    for line in checklist_data.split('\n'):
        stripped = line.strip()
        if not stripped:
            continue
        
        # Detect headers (markdown ## or all caps)
        if stripped.startswith('##'):
            doc.add_heading(stripped.lstrip('#').strip(), level=2)
        elif stripped.startswith('#'):
            doc.add_heading(stripped.lstrip('#').strip(), level=1)
        elif stripped.startswith(('- ', '* ', '☐ ', '☑ ', '•')):
            # Bullet items
            clean_text = stripped.lstrip('-*☐☑• ').strip()
            doc.add_paragraph(clean_text, style='List Bullet')
        elif stripped[0].isdigit() and '.' in stripped[:4]:
            # Numbered items
            doc.add_paragraph(stripped, style='List Number')
        else:
            doc.add_paragraph(stripped)
    
    # Footer
    doc.add_paragraph("\n")
    doc.add_paragraph("─" * 60)
    footer = doc.add_paragraph("Generated by Government Tender Simplifier — AI-Powered Bid Preparation Tool")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc_io = io.BytesIO()
    doc.save(doc_io)
    doc_io.seek(0)
    return doc_io


def generate_eligibility_report_docx(report: dict, vendor_profile: dict, tender_title: str) -> io.BytesIO:
    """
    Generate a formatted DOCX eligibility report with pass/fail details.
    """
    doc = Document()
    
    # Title
    title = doc.add_heading("Eligibility Compliance Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Overall Status
    status = report.get("overall_status", "UNKNOWN")
    message = report.get("message", "")
    doc.add_heading(f"Overall Status: {status}", level=1)
    doc.add_paragraph(message)
    
    # Vendor Details
    doc.add_heading("Vendor Profile", level=2)
    vendor_fields = [
        ("Company Name", vendor_profile.get("company_name", "N/A")),
        ("Annual Turnover (Lakhs)", vendor_profile.get("turnover", "N/A")),
        ("Experience (Years)", vendor_profile.get("experience_years", "N/A")),
        ("Projects Completed", vendor_profile.get("projects_completed", "N/A")),
        ("MSME Registered", "Yes" if vendor_profile.get("msme_status") else "No"),
        ("ISO Certified", "Yes" if vendor_profile.get("iso_certified") else "No"),
        ("Certifications", ", ".join(vendor_profile.get("certifications", [])) or "None"),
    ]
    
    # Vendor details table
    table = doc.add_table(rows=1, cols=2)
    table.style = 'Light List Accent 1'
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = 'Field'
    hdr_cells[1].text = 'Value'
    
    for field_name, field_value in vendor_fields:
        row_cells = table.add_row().cells
        row_cells[0].text = str(field_name)
        row_cells[1].text = str(field_value)
    
    doc.add_paragraph("")
    
    # Criterion-Level Results
    doc.add_heading("Criterion-Level Assessment", level=2)
    
    details = report.get("details", [])
    if details:
        results_table = doc.add_table(rows=1, cols=4)
        results_table.style = 'Light List Accent 1'
        hdr = results_table.rows[0].cells
        hdr[0].text = 'Criterion'
        hdr[1].text = 'Required'
        hdr[2].text = 'Vendor Value'
        hdr[3].text = 'Status'
        
        for item in details:
            row = results_table.add_row().cells
            row[0].text = item.get("criterion", "N/A")
            row[1].text = str(item.get("required", "N/A"))
            row[2].text = str(item.get("vendor_value", "N/A"))
            row[3].text = item.get("status", "N/A")
    
    doc.add_paragraph("")
    
    # Detailed Reasoning
    doc.add_heading("Detailed Reasoning", level=2)
    for item in details:
        status_icon = "✅" if item["status"] == "PASS" else "❌" if item["status"] == "FAIL" else "⚠️"
        doc.add_paragraph(f"{status_icon} {item['criterion']}", style='List Bullet')
        doc.add_paragraph(f"   Reasoning: {item.get('reasoning', 'N/A')}")
        if item.get("source_text"):
            doc.add_paragraph(f"   Source: \"{item['source_text']}\"")
    
    # Summary Stats
    doc.add_heading("Summary", level=2)
    doc.add_paragraph(f"Total Criteria Evaluated: {report.get('total_criteria', 0)}")
    doc.add_paragraph(f"Passed: {report.get('passed', 0)}")
    doc.add_paragraph(f"Failed: {report.get('failed', 0)}")
    doc.add_paragraph(f"Needs Review: {report.get('needs_review', 0)}")
    
    # Footer
    doc.add_paragraph("\n")
    doc.add_paragraph("─" * 60)
    doc.add_paragraph(f"Tender: {tender_title}")
    doc.add_paragraph(f"Generated: {datetime.now().strftime('%d-%m-%Y %H:%M')}")
    footer = doc.add_paragraph("Generated by Government Tender Simplifier — AI-Powered Bid Preparation Tool")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc_io = io.BytesIO()
    doc.save(doc_io)
    doc_io.seek(0)
    return doc_io


def generate_zip_package(tender_title: str, checklist_docx: io.BytesIO, report_docx: io.BytesIO) -> io.BytesIO:
    """
    Combines the Checklist and Eligibility Report into a single ZIP file.
    """
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        # Reset pointers
        checklist_docx.seek(0)
        report_docx.seek(0)
        
        # Add to zip
        zip_file.writestr(f"Checklist_{tender_title.replace('.pdf', '')}.docx", checklist_docx.read())
        zip_file.writestr(f"Eligibility_Report_{tender_title.replace('.pdf', '')}.docx", report_docx.read())
        
    zip_buffer.seek(0)
    return zip_buffer